### ISSUE TITLE
not passing --model_path causes failure with cryptic error message

### ISSUE THREAD

**Issue by coleslaw481** [idekerlab/cellmaps_image_embedding#5]
* cellmaps_image_embedding version: 0.1.0a7 and earlier
* Python version: 3.8
* Operating System: mac

### Description
Running the tool without specifying ``--model_path`` results in this cryptic error message:

### What I Did

```
cellmaps_image_embeddingcmd.py 2.newimage_embeddingfake2 --fold 2 --inputdir 1.image_download  -vvvv
```

Error
```
2023-08-01 17:23:23,692 ERROR 489ms cellmaps_image_embeddingcmd.py::main():133 Caught exception: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/Users/churas/anaconda3/envs/python382/bin/cellmaps_image_embeddingcmd.py", line 119, in main
    gen = DensenetEmbeddingGenerator(os.path.abspath(theargs.inputdir),
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/site-packages/cellmaps_image_embedding/runner.py", line 207, in __init__
    self._model_path = os.path.abspath(model_path)
  File "/Users/churas/anaconda3/envs/python382/lib/python3.8/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by coleslaw481** [comment]
Fixed in a different way. If no ``--model_path`` is set then the code will download the model from the URL set by default.
